apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cruzingress
  labels:
    name: cruzingress
spec:
  rules:
  - host: cruzingress.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: node-server-service
            port: 
              number: 3011
